name: trendy-workflow-actions/debug-print-secret

on:
  workflow_call:
    secrets:
      SECRET_01:
        required: true
      SECRET_02:
        required: false
      SECRET_03:
        required: false
      SECRET_04:
        required: false
      SECRET_05:
        required: false

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Debug - print SECRET_01
        run: |
          echo "SECRET_01= ${{ secrets.SECRET_01 }}" |  sed 's/./& /g'
      - name: Debug - print SECRET_02
        run: |
          echo "SECRET_02= ${{ secrets.SECRET_02 }}" |  sed 's/./& /g'
      - name: Debug - print SECRET_03
        run: |
          echo "SECRET_03= ${{ secrets.SECRET_03 }}" |  sed 's/./& /g'
      - name: Debug - print SECRET_04
        run: |
          echo "SECRET_04= ${{ secrets.SECRET_04 }}" |  sed 's/./& /g'
      - name: Debug - print SECRET_05
        run: |
          echo "SECRET_05= ${{ secrets.SECRET_05 }}" |  sed 's/./& /g'
      