name: trendy-workflow-actions/deploy-in-docker

on:
  workflow_call:
    inputs:     
      do-branch-filtering-before-start:
        required: false
        default: true
        type: boolean
      do-step-notify-teams-on-failure:
        required: false
        default: true
        type: boolean
      do-step-copy-platform-config:
        required: false
        default: true
        type: boolean
      do-step-create-npmrc:
        required: false
        default: true
        type: boolean
      step-notify-teams-job-name:
        required: true
        default: '?EnvName?'
        type: string
      branch-name-for-branch-filtering-before-start:
        required: false
        default: 'refs/heads/main'
        type: string
      step-configure-aws-region:
        required: false
        default: 'eu-west-1'
        type: string
      step-copy-platform-config-setup-json:
        required: false
        default: ''
        type: string
      step-run-deployment-in-docker-command:
        required: true
        default: '?Command?'
        type: string
      
    secrets:
      MSTEAMS_WEBHOOK:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      NPM_ACCESS_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  Deploy-to-aslive:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    env:
      JOB_NAME: ${{ github.workflow }}-${{ github.run_number }}-${{ github.sha }}
      VERSION: ${{ github.run_number }}-${{ github.sha }}
      GITHUB_TOKEN: dummy-token
    if: ${{ !inputs.do-branch-filtering-before-start || github.ref == inputs.branch-name-for-branch-filtering-before-start }}
    steps:
      - name: Print input paramters
        run: |
          echo 'inputs:'
          echo '${{toJSON(inputs)}}'
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Notify Teams
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: ${{ inputs.do-step-notify-teams-on-failure }}
        with:
          github-token: ${{ github.token }} # Use built-in more restricted token
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          card-layout-exit: complete
          show-on-start: false
          show-on-failure: true
          custom-facts: |
            - name: Job Name
              value: '${{ inputs.step-notify-teams-job-name }}'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.step-configure-aws-region }}
      - name: Copy platform-config from s3
        if: ${{ inputs.do-step-copy-platform-config }}
        run: |
          COPY_PLATFORM_CONFIG_INPUT_JSON='${{inputs.step-copy-platform-config-setup-json}}'
          COPY_PLATFORM_CONFIG_INPUT_SRC=""
          COPY_PLATFORM_CONFIG_INPUT_DEST=""
          INPUT_DEST=""
          for row in $(echo $COPY_PLATFORM_CONFIG_INPUT_JSON | jq -c .items[]); 
          do 
          COPY_PLATFORM_CONFIG_INPUT_SRC=$(jq -r '.src' <<< "${row}");
          COPY_PLATFORM_CONFIG_INPUT_DEST=$(jq -r '.dest' <<< "${row}");
          echo "run: aws s3 sync $COPY_PLATFORM_CONFIG_INPUT_SRC $COPY_PLATFORM_CONFIG_INPUT_DEST";
          aws s3 sync $COPY_PLATFORM_CONFIG_INPUT_SRC $COPY_PLATFORM_CONFIG_INPUT_DEST;
          done
      - name: Create .npmrc
        if: ${{ inputs.do-step-create-npmrc }}
        run: |
          echo "@mergermarket:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org" >> .npmrc      
      - name: Run deployment in Docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ${{ inputs.step-run-deployment-in-docker-command }}
