name: 'Run all commands'
description: 'Runs all build commands'
inputs:
  docker-username:
    description: 'docker username'
    required: true
  docker-password:
    description: 'docker password'
    required: true
  github-token:
    description: 'github token'
    required: true
  pre-commands-json:
    description: 'pre build command json'
    required: true
  commands-json:
    description: 'build command json'
    required: true
  post-commands-json:
    description: 'post build command json'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run pre commands
      uses: mergermarket/trendy-workflow-actions/.github/actions/run-commands@main
      with:
        github-token: ${{ inputs.github-token }}
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}
        commands-json: ${{ inputs.pre-commands-json }}
    - name: Run commands
      uses: mergermarket/trendy-workflow-actions/.github/actions/run-commands@main
      with:
        github-token: ${{ inputs.github-token }}
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}
        commands-json: ${{ inputs.commands-json }}
    - name: Run post commands
      uses: mergermarket/trendy-workflow-actions/.github/actions/run-commands@main
      with:
        github-token: ${{ inputs.github-token }}
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}
        commands-json: ${{ inputs.post-commands-json }}
