name: trendy-workflow-actions/report-workflow-run

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: "ubuntu-latest"
        type: string
      report-api-host:
        required: false
        default: "aslive-api.ionanalytics.com"
        type: string
      team:
        required: false
        default: "Unknown Team"
        type: string
      group:
        required: false
        default: ""
        type: string
      scheduleType:
        required: false
        default: "none"
        type: string
      branch-filtering:
        required: false
        default: true
        type: boolean
      branch-name-for-filtering:
        required: false
        default: "refs/heads/main"
        type: string
    secrets:
      GIT_ACTIONS_MONITOR_API_KEY:
        required: true

jobs:
  ReportWorkflowRun:
    runs-on: [ "${{ inputs.runs-on }}" ]
    permissions:
      actions: read
      contents: read
    if: ${{ !inputs.branch-filtering || github.ref == inputs.branch-name-for-filtering }}
    steps:
      - name: Report Workflow Run
        env:
          WORKFLOW_RUN_JSON: ${{ toJson(github.event.workflow_run) }}
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "inputs.branch-name-for-filtering: ${{ inputs.branch-name-for-filtering }}"
          echo "Report about: ${{github.event.workflow_run.html_url}}" 
          curl --location 'https://${{ inputs.report-api-host }}/git-actions-monitor/workflow-run' \
          --header 'x-api-key: ${{ secrets.GIT_ACTIONS_MONITOR_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "team": "${{ inputs.team }}",
            "group": "${{ inputs.group }}",
            "scheduleType": "${{ inputs.scheduleType }}",
            "run": '"$WORKFLOW_RUN_JSON"'
            }'
